---
name: compile
run-name: Verify code compilation targetting Linux with both make and ninja
on: [pull_request]
jobs:
  make-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up cmake
        run: sudo apt update && sudo apt install cmake
      - name: Configure the build
        run: cmake .
      - name: Build the program
        run: cmake --build .
  ninja-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up cmake and ninja-build
        run: sudo apt update &&  sudo apt install cmake ninja-build
      - name: Configure the build
        run: cmake -GNinja .
      - name: Build the program
        run: cmake --build .
  make-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up cmake
        run: sudo apt update && sudo apt install cmake clang
      - name: Configure the build
        run: CC=clang cmake .
      - name: Build the program
        run: cmake --build .
  ninja-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up cmake and ninja-build
        run: sudo apt update &&  sudo apt install cmake ninja-build clang
      - name: Configure the build
        run: CC=clang cmake -GNinja .
      - name: Build the program
        run: cmake --build .
